Improved admin test suite.

diff --git a/bin/_test-suite b/bin/_test-suite
--- a/bin/_test-suite
+++ b/bin/_test-suite
@@ -16,10 +16,7 @@
 #C: You should have received a copy of the GNU General Public License
 #C: along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-# TO DO: use 'cylc ping' to determine if the suite is running when it
-# should be.
-
-set -e; trap "echo 'TEST FAILED (see output log)'" ERR
+set -e; trap "echo 'TEST FAILED (see test-suite.out)'" ERR
 
 usage() {
     echo "USAGE: cylc [admin] test-suite [--help]"
@@ -58,70 +55,56 @@ if [[ $# != 0 ]]; then
     fi
 fi
 
+if [[ -z $TMPDIR ]]; then
+    echo "ERROR: export TMPDIR before running this script."
+fi
+mkdir -p $TMPDIR
+
 # seconds since epoch
 SSE=$( date +%s )
 
-SUITE_REG=test.$SSE
-SUITE_DIR=$TMPDIR
+SUITE_DEF=$CYLC_DIR/examples/test
+SUITE_REG=testsuite.$SSE
+SUITE_DIR=$TMPDIR/$SUITE_REG
 
-CYLC_VERSION=$( cylc -v )
-if [[ $CYLC_VERSION == "THIS IS NOT A VERSIONED RELEASE" ]]; then
-    # we are in a cylc git repository - get most recent tag
-    # and append seconds since epoch.
-    CYLC_VERSION=$( git tag | tail -1 )
-fi
-CYLC_VERSION=$( echo $CYLC_VERSION | tr '.' 'p' )
-
-# take the first matching suite of this cylc version in the central database
-# (cylc admin create-cdb appends $SSE if run from a git repository)
-SOURCE_SUITE=$( cylc db pr -c cylc-${CYLC_VERSION}.*\.admin\.test | sed -e 's/ |.*//' | head -1 )
-if [[ -z $SOURCE_SUITE ]]; then
-    echo "ERROR, admin.test suite not found!"
-    echo "Have you run 'cylc admin create-cdb'?"
-    exit 1
-fi
-
-# IMPORT THE SUITE
-echo -n ">> IMPORTING $SOURCE_SUITE ... "
-cylc db import $SOURCE_SUITE $SUITE_REG $SUITE_DIR
+echo -n ">> COPYING $SUITE_DEF and REGISTERING it as $SUITE_REG ... "
+cp -r $SUITE_DEF $SUITE_DIR
+cylc db reg $SUITE_REG $SUITE_DIR
+echo done
 
 # log file for stdout and stderr
 OUT=test.out; OUT_SCHED=test-suite.out
 rm -f $OUT $OUT_SCHED
-
-# suite log
-LOG=$( cylc info get-config $SUITE_REG cylc logging directory )/log
-# remove old test log
-rm -rf $LOG
 
 # START UP THE TEST SUITE
 echo
 echo ">> STARTING at 2010010106, with TASK X to FAIL at 2010010112"
 export TEST_X_FAIL_TIME=2010010112
 
-# startup errors (e.g. due to lockserver denying access to the suite)
-# won't be trapped here because we run cylc in the background!
+# startup errors aren't trapped here because we run cylc in the background
 cylc run --debug $SUITE_REG 2010010106 >> $OUT_SCHED 2>&1 &
-echo -n "   Will wait 5 seconds for startup ... "
-sleep 5
-echo done
 
-# now check for startup errors, as just described.
-if grep '_run failed:  1' $OUT_SCHED  > /dev/null; then
-    cat $OUT_SCHED
-    munge 2> /dev/null # activate trap with a non-existent command
+echo ">> waiting 10 seconds for startup"
+for i in {1..10}; do
+    sleep 1
+    echo -n "."
+    cylc ping $SUITE_REG > /dev/null 2>&1 && break
+done
+echo done
+if cylc ping $SUITE_REG; then
+    echo ">> Suite started."
+else
+    echo "ERROR: suite failed to start. Check test-suite.out"
+    exit 1
 fi
 
 # WAIT FOR ALL TASKS AT 2010010112 TO FINISH 
 # at which point the suite is stalled because X failed.
-
 echo
 echo ">> WAITING for X%2010010112 to fail"
 echo -n "   ."
-READY=false
-while ! $READY; do
-    READY=true
-    ! grep "X%2010010112 failed" $LOG > /dev/null 2>&1 && READY=false
+while true; do
+    cylc dump $SUITE_REG | grep 'X, 2010010112, failed' > /dev/null 2>&1 && break
     echo -n .
     sleep 1
 done
@@ -130,12 +113,8 @@ echo done
 echo
 echo ">> WAITING for suite to stall at 2010010112 due to failed X"
 echo -n "   ."
-READY=false
-while ! $READY; do
-    READY=true
-    for TASK in A B C D E F; do
-        ! grep "${TASK}%2010010106 succeeded" $LOG > /dev/null 2>&1 && READY=false
-    done
+while true; do
+    cylc dump $SUITE_REG | grep running > /dev/null 2>&1 || break
     echo -n .
     sleep 1
 done
@@ -164,16 +143,25 @@ echo done
 
 # WAIT FOR THE SUITE TO FINISH AT 2010010212
 echo
-echo ">> WAITING for the suite to shut down at 2010010112"
+echo ">> WAITING for the suite to shut down"
 echo -n "   ."
-READY=false
-while ! $READY; do
-    READY=true
-    ! grep "ALL TASKS FINISHED" $LOG > /dev/null 2>&1 && READY=false
+while true; do
+    cylc ping $SUITE_REG > /dev/null || break
     echo -n .
     sleep 1
 done
 echo done
+
+# did it shut down for the right reasons? check suite log:
+REASON=$( cylc log $SUITE_REG | tail -2 | head -1 | sed -e 's/.*- //' )
+if [[ $REASON != 'ALL TASKS FINISHED OR HELD' ]]; then
+    echo "ERROR, the suite seems to have shut down for the wrong reasons:"
+    echo "Here's the last 10 lines of the suite log:"
+    cylc log $SUITE_REG | tail -10
+    exit 1
+fi
+
+echo "Reason for shutdown: $REASON"
 
 # RUN A SINGLE TASK
 # can be one that completes successfully or fails, it doesn't matter.
@@ -187,31 +175,25 @@ echo "TASK OUTPUT LOGS:"
 echo "  $STDOUT"
 echo "  $STDERR"
 echo -n "   ."
-READY=false
-while ! $READY; do
-    egrep 'cylc \(submit.*\): prep%2010010106 succeeded' $STDOUT 2> /dev/null && READY=true
+while true; do
+    egrep 'cylc \(submit.*\): prep%2010010106 succeeded' $STDOUT 2> /dev/null && break
     echo -n .
     sleep 1
 done
-echo done
-
-# DELETE THE SUITE DEFINITION DIRECTORY
-echo
-echo -n ">> DELETING suite definition directory ..."
-rm -rf $SUITE_DIR
-echo done
-
-# UNREGISTER THE test SUITE
-echo
-echo -n ">> UNREGISTERING suite test ..."
-cylc unregister $SUITE_REG >> $OUT 2>&1
 echo done
 
 # FINISHED
 echo 
 echo ">> TEST OUTPUT LOGS:"
 ls -l $OUT $OUT_SCHED
-echo ">> CYLC MAIN LOG FOR THE TEST:"
-ls -l $LOG
+echo ">> CYLC SUITE LOG FOR THE TEST:"
+ls -l $( cylc log $SUITE_REG -p )
+
+# UNREGISTER THE test SUITE and DELETE the suite definition
+echo
+echo -n ">> UNREGISTERING suite test ..."
+cylc unregister --delete -f $SUITE_REG >> $OUT 2>&1
+echo done
+
 echo
 echo ">> DONE"
