cylc help fixes
Use 1st sentence of JOSS paper as description in `cylc help`.
Fix: `cylc help control ...`.
Fix: `cylc CATEGORY COMMAND --help`
Fix: `cylc trigger` abbreviation example.
Mention `cylc COMMAND --help`.

diff --git a/bin/cylc b/bin/cylc
--- a/bin/cylc
+++ b/bin/cylc
@@ -36,7 +36,7 @@ get_version() {
     # Else we must be in a standalone cylc folder/tarball with no verion info.
     # (make has not yet been run)
     else
-        echo "No version is set, cylc must be built first. Aborting..."
+        echo "No version is set, cylc must be built first. Aborting..." >&2
         exit 1
     fi
 }
@@ -78,14 +78,14 @@ help_util() {
     fi
     # for cases 'cylc --help CATEGORY COMMAND'
     if [[ $# -gt 1 &&  "${HELP_OPTS[*]} " == *"$UTIL"* && \
-          "${CATEGORIES[*]} " == *" $1 "* ]]; then
+          " ${CATEGORIES[*]} " == *" $1 "* ]]; then
         local COMMAND="${CYLC_HOME_BIN}/cylc-$2"
         exec "${COMMAND}" "--help"  
     fi
     # Check if this is a help command, not containing a category qualifier
     if [[ $# -gt 1  && "${HELP_OPTS[*]} " == *"${UTIL}"* && 
-          "${CATEGORIES[*]} " != *" $1 "* &&
-          "${CATEGORIES[*]} " != *" $2 "* ]]; then
+          " ${CATEGORIES[*]} " != *" $1 "* &&
+          " ${CATEGORIES[*]} " != *" $2 "* ]]; then
         local COMMAND="${CYLC_HOME_BIN}/cylc-${UTIL}"
         exec "${COMMAND}" "--help"
     fi
@@ -110,10 +110,10 @@ Options:
   --long            print cylc version and location of cylc installation
 __HELP__
             return
-        elif ls cylc-${1}* 2>'/dev/null'; then
-            local COMMAND="${CYLC_HOME_BIN}/$(ls "cylc-$1"*)"
-            exec "${COMMAND}" "--help"
-        elif (( "$(wc -l <<<"$(ls cylc-${1}* 2>/dev/null)")" > 1 )); then
+        elif test -x "cylc-$1"*; then
+            local COMMAND="${CYLC_HOME_BIN}/$(echo "cylc-$1"*)"
+            exec "${COMMAND}" '--help'
+        elif (( "$(wc -l <<<"$(ls cylc-$1* 2>/dev/null)")" > 1 )); then
             abort_ambiguous_command "$1"
         else
             abort_bad_command "$1"
@@ -126,7 +126,7 @@ __HELP__
         exec "${COMMAND}" "$@"
     fi
     # Deal with cases like 'cylc --help [COMMAND/CATEGORY]'
-    if [[ $# -gt 1 && -f "$(ls cylc-${2}* 2>/dev/null)" ]]; then
+    if [[ $# -gt 1 && -f "$(ls "cylc-$2"* 2>'/dev/null')" ]]; then
         local COMMAND="${CYLC_HOME_BIN}/$(ls "cylc-$2"*)"
         exec "${COMMAND}" "--help"
     fi
@@ -183,10 +183,10 @@ abort_bad_command() {
 }
 
 abort_ambiguous_command() {
-    echo "\"$1\" is ambiguous."
-    echo "These commands match the abbreviation \"$1\":"
+    echo "\"$1\" is ambiguous." >&2
+    echo "These commands match the abbreviation \"$1\":" >&2
     sed "s,${CYLC_HOME_BIN}/cylc-,," \
-        <<<"$(ls "${CYLC_HOME_BIN}/cylc-$1"* 2>/dev/null)"
+        <<<"$(ls "${CYLC_HOME_BIN}/cylc-$1"* 2>/dev/null)" >&2
     exit 1
 }
 
@@ -223,8 +223,7 @@ control|information|all|task|license|GPL|admin|preparation|hook|discovery\
     if (( $# == 0 )); then
         help_util "${UTIL}"
     fi
-    if [[ $# -ge 1 && "${HELP_OPTS[*]} " == *"$1"* \
-            || $# -ge 2 && "${HELP_OPTS[*]} " == *"$2"* ]]; then
+    if [[ $# -ge 1 && "${HELP_OPTS[*]} " == *"$1"* ]]; then
         help_util "${UTIL}"
     fi
     UTIL="$1"
