Check pyc files line up before running complete test battery.

diff --git a/bin/cylc-test-battery b/bin/cylc-test-battery
--- a/bin/cylc-test-battery
+++ b/bin/cylc-test-battery
@@ -80,6 +80,16 @@ if [[ "$PWD" != "$CYLC_DIR" ]]; then
     echo "[INFO] cd \"$CYLC_DIR\""
     cd "$CYLC_DIR"
 fi
+
+echo "[INFO] Checking .pyc files match .py files..."
+py_files=$(find "$CYLC_DIR" -name "*.pyc" -type f | sed "s/pyc$/py/g")
+ls $py_files 1> /dev/null
+if [ $? -gt 0 ]; then
+    echo "[ERROR] Aborting test battery, .pyc files do not match .py files"
+else
+    echo "[INFO] ...ok"
+fi
+
 if perl -e 'use Test::Harness 3.00' 2>/dev/null; then
     NPROC=$(cylc get-global-config '--item=process pool size')
     if [[ -z "${NPROC}" ]]; then
