ammendments to help features

diff --git a/bin/cylc b/bin/cylc
--- a/bin/cylc
+++ b/bin/cylc
@@ -37,8 +37,6 @@ get_version() {
         fi
     # Else we must be in a standalone cylc folder/tarball with no verion info.
     # (make has not yet been run)
-    # TODO what if the user has just run git init? That would not be a proper
-    # git clone of the cylc repo...
     else
         echo "No version is set, cylc must be built first. Aborting..."
         exit 1
@@ -56,7 +54,6 @@ print_version() {
 }
 
 init_cylc() {
-    #set -eu
     CYLC_HOME_BIN="$(dirname "$(readlink -f "$0")")"
     CYLC_HOME="$(dirname "${CYLC_HOME_BIN}")"
     CYLC_NS="$(basename $0)"
@@ -74,7 +71,8 @@ init_cylc() {
 help_util() {
     # Deals with form 'cylc [COMMAND] --help'
     cd "${CYLC_HOME_BIN}"
-   # deal with graph which is a weird edge case...
+    echo $UTIL
+    # deal with graph which is a weird edge case...
     if [[ "$@" == "graph" ]]; then
         local COMMAND="${CYLC_HOME_BIN}/cylc-graph"
         exec "${COMMAND}" "--help"
@@ -83,27 +81,38 @@ help_util() {
     if [[ (( "$#" -gt 1 )) && "${HELP_OPTS[*]} " == *" ${UTIL} "* && 
           "${CATEGORIES[*]} " != *" $1 "* &&
           "${CATEGORIES[*]} " != *" $2 "* ]]; then
-        local COMMAND="${CYLC_HOME_BIN}/cylc-$1"
+        local COMMAND="${CYLC_HOME_BIN}/cylc-${UTIL}"
         exec "${COMMAND}" "--help"
     fi
+    # If category name is used, call the help func with the category
+    if [[ " ${CATEGORIES[*]} " == *" ${UTIL} "* 
+            || " ${HELP_OPTS[*]} " == *" ${UTIL} "* ]]; then
+        local COMMAND="${CYLC_HOME_BIN}/cylc-help"
+        exec "${COMMAND}" "${UTIL}"
+    fi
+
+    # If category name is used as second arg, call the help func with the category
+    if [[ (( "$#" -gt 1 )) &&  "${CATEGORIES[*]} " == *" ${1} "* 
+            || " ${HELP_OPTS[*]} " == *" ${1} "* ]]; then
+        local COMMAND="${CYLC_HOME_BIN}/cylc-help"
+        exec "${COMMAND}" "$@"
+    fi
     # Deal with cases like 'cylc --help [COMMAND/CATEGORY] or cylc [CATEGORY]'   
-    if [[ (( "$#" -ge 1 )) && -f "$(ls cylc-${1}* 2>/dev/null)" ]]; then
+    if (( "$#" >= 1 )); then
+        if [[  -f "$(ls cylc-${1}* 2>/dev/null)" ]]; then
         local COMMAND="${CYLC_HOME_BIN}/$(ls "cylc-$1"*)"
         exec "${COMMAND}" "--help"
+        elif (( "$(wc -l <<<"$(ls cylc-${1}* 2>/dev/null)")" > 1 )); then
+            abort_ambiguous_command "$1"
+        else
+            abort_bad_command "$1"
+        fi
     fi
     # Deal with cases like 'cylc --help [COMMAND/CATEGORY]'
     if [[ (( "$#" -gt 1 )) && -f "$(ls cylc-${2}* 2>/dev/null)" ]]; then
         local COMMAND="${CYLC_HOME_BIN}/$(ls "cylc-$2"*)"
         exec "${COMMAND}" "--help"
     fi
-    
-    # If category name is used, call the help func with the category
-    if [[ " ${CATEGORIES[*]} " == *" ${UTIL} "* 
-            || " ${HELP_OPTS[*]} " == *" ${UTIL} "* ]]; then
-        local COMMAND="${CYLC_HOME_BIN}/cylc-help"
-        exec "${COMMAND}" "$@"
-    fi
-    
     # If not a category or not an actual command in the bin dir, exit
     if [[ ! -f "$(ls "cylc-${UTIL}"*)" ]]; then
         echo "${UTIL}: unknown utility. Abort." >&2
@@ -144,35 +153,25 @@ path_lead() {
 }
 
 abort_bad_command() {
-    echo "${CYLC_NS}: ${UTIL}: unknown utility. Abort." >&2
+    echo "${CYLC_NS}: $1: unknown utility. Abort." >&2
     echo "Type \"${CYLC_NS} help all\" for a list of utilities." >&2
     exit 1
 }
 
 abort_ambiguous_command() {
-    echo "\"${UTIL}\" is too ambiguous to be a valid Cylc command abbreviation."
-    echo "These commands match the abbreviation \"${UTIL}\":"
-    sed -r "s,${CYLC_HOME_BIN}/cylc-,," <<<"${commands_match}"
-#    ls "${CYLC_HOME_BIN}/cylc-${UTIL}"* 2>/dev/null \
-#       | sed -r "s,${CYLC_HOME_BIN}/cylc-,,"
+    echo "\"$1\" is ambiguous."
+    echo "These commands match the abbreviation \"$1\":"
+    sed -r "s,${CYLC_HOME_BIN}/cylc-,," <<<"$(ls "${CYLC_HOME_BIN}/cylc-$1"* 2>/dev/null)"
     exit 1
 }
 
 run_cylc_command_matched() {
-#    COMMAND=$(ls "${CYLC_HOME_BIN}/cylc-${UTIL}"*)
-#    if [[ ! -f "${COMMAND}" || ! -x "${COMMAND}" ]]; then
-#        abort_bad_command
-#    fi
     CYLC_UTIL="$(sed -r "s,${CYLC_HOME_BIN}/cylc-,," <<<"${commands_match}")"
     export CYLC_UTIL
     exec "${commands_match}" "$@"
 }
 
 run_cylc_command() {
-#    COMMAND="${commands_match}"
-#    if [[ ! -f "${COMMAND}" || ! -x "${COMMAND}" ]]; then
-#        abort_bad_command
-#    fi
     CYLC_UTIL="${UTIL}"
     export CYLC_UTIL
     exec "${CYLC_HOME_BIN}/cylc-${UTIL}" "$@"
@@ -199,18 +198,20 @@ control|information|all|task|license|GPL|admin|preparation|hook|discovery\
         |utility|util|prep|con|info)
     if (( "$#" == 0 )); then
         help_util "${UTIL}"
-    elif (( "$#" > 0 )); then
-        UTIL="$1"
-        # Discard the category qualifier argument by shifting
-        # the arguments along by 1.
-        shift 1
     fi
+    if [[ (( "$#" > 0 )) && "${HELP_OPTS[*]} " == *"${2}"* ]]; then
+        help_util "${UTIL}"
+    fi
+    UTIL="$1"
+    # Discard the category qualifier argument by shifting
+    # the arguments along by 1.
+    shift 1
     :;;
 help|h|?|--help|-h)
     help_util "$@"
     exit 0
     :;;
-version|--version|-V)
+version|--version|-V|-v)
     print_version "$@"
     exit 0
     :;;
@@ -235,7 +236,7 @@ fi
 
 # Abort if no matches to command abbrev, list matches if multiple matches
 if (( "$num_commands_match" == 0 )); then
-    abort_bad_command
+    abort_bad_command "${UTIL}"
 # Now try and match abbreviated commands.
 elif (( "$num_commands_match" == 1 )); then
     run_cylc_command_matched "$@"
@@ -245,6 +246,6 @@ elif (( "$num_commands_match" == 1 )); then
 elif [[ (("$num_commands_match" > 1)) && -f "${CYLC_HOME_BIN}/cylc-${UTIL}" ]] ; then
     exec "${CYLC_HOME_BIN}/cylc-${UTIL}" "@"
 else
-    abort_ambiguous_command 
+    abort_ambiguous_command "${UTIL}"
 fi
 
