Replace TMPDIR with $CYLC_TMPDIR

diff --git a/bin/cylc-create-cdb b/bin/cylc-create-cdb
--- a/bin/cylc-create-cdb
+++ b/bin/cylc-create-cdb
@@ -42,8 +42,12 @@ if [[ $1 == '-h' ]] || [[ $1 == '--help' ]]; then
 fi
 
 if [[ -z $CYLC_DIR ]]; then
-    echo "\$CYLC_DIR is not defined. Run this script via the cylc main"
-    echo "command interface: 'cylc admin create-cdb'"
+    echo "ERROR: \$CYLC_DIR is not defined. Run this script via" >&2
+    echo "the main command interface: 'cylc admin create-cdb'" >&2
+    exit 1
+fi
+if [[ -z $CYLC_TMPDIR ]]; then
+    echo "ERROR: \$CYLC_TMPDIR is not defined" >&2
     exit 1
 fi
 
@@ -84,7 +88,7 @@ cylc unregister $TOP
 
 echo " + Importing copies of examples to your private database"
 # We don't want the admin user accidentally modifying the originals.
-cylc import ${USER}.$TOP $TOP $TMPDIR
+cylc import ${USER}.$TOP $TOP $CYLC_TMPDIR
 
 # Determine CDB directory location
 # The following no longer works (see comment in lib/cylc/__init__.py)
diff --git a/bin/cylc-test-db b/bin/cylc-test-db
--- a/bin/cylc-test-db
+++ b/bin/cylc-test-db
@@ -31,15 +31,16 @@ if [[ $# != 0 ]]; then
     if [[ $1 == "--help" ]]; then
         exit 0
     else
-        echo "ERROR: illegal command line arguments"
+        echo "ERROR: illegal command line arguments" >&2
         exit 1
     fi
 fi
 
-if [[ -z $TMPDIR ]]; then
-    echo "ERROR: export TMPDIR before running this script."
+if [[ -z $CYLC_TMPDIR ]]; then
+    echo "ERROR, undefined environment variable: \$CYLC_TMPDIR" >&2
+    exit 1
 fi
-mkdir -p $TMPDIR
+mkdir -p $CYLC_TMPDIR
 
 # seconds since epoch
 SSE=$( date +%s )
@@ -52,12 +53,12 @@ REG4=${GRP}.waaaz123
 REG5=${GRP}.impppt123
 
 # clean up old suite def dirs from any aborted previous run
-rm -rf $TMPDIR/$REG4
-rm -rf $TMPDIR/$REG5
+rm -rf $CYLC_TMPDIR/$REG4
+rm -rf $CYLC_TMPDIR/$REG5
 
 echo
 echo "> TEST1: register a cylc example suite as $REG1"
-DEFDIR=$TMPDIR/test-db.$SSE
+DEFDIR=$CYLC_TMPDIR/test-db.$SSE
 cp -r $CYLC_DIR/examples/admin/test $DEFDIR
 echo cylc db reg $REG1 $DEFDIR
 cylc db reg $REG1 $DEFDIR
@@ -74,8 +75,8 @@ cylc db register $REG3 $(cylc db get $REG2)
 
 echo
 echo "> TEST4: copy the suite to $REG4"
-echo cylc db copy $REG2 $REG4 $TMPDIR/$REG4
-cylc db copy $REG2 $REG4 $TMPDIR/$REG4
+echo cylc db copy $REG2 $REG4 $CYLC_TMPDIR/$REG4
+cylc db copy $REG2 $REG4 $CYLC_TMPDIR/$REG4
 
 echo
 echo "> TEST5: print LDB reg group $GRP"
@@ -101,8 +102,8 @@ cylc db pr --central ${USER}.${GRP}
 
 echo
 echo "> TEST9: import central $REG4 as $REG5"
-echo cylc db imp ${USER}.$REG4 $REG5 $TMPDIR/$REG5
-cylc db imp ${USER}.$REG4 $REG5 $TMPDIR/$REG5
+echo cylc db imp ${USER}.$REG4 $REG5 $CYLC_TMPDIR/$REG5
+cylc db imp ${USER}.$REG4 $REG5 $CYLC_TMPDIR/$REG5
 
 echo
 echo "> TEST10: delete $REG2 from CDB"
diff --git a/bin/cylc-test-suite b/bin/cylc-test-suite
--- a/bin/cylc-test-suite
+++ b/bin/cylc-test-suite
@@ -55,17 +55,18 @@ if [[ $# != 0 ]]; then
     fi
 fi
 
-if [[ -z $TMPDIR ]]; then
-    echo "ERROR: export TMPDIR before running this script."
+if [[ -z $CYLC_TMPDIR ]]; then
+    echo "ERROR, undefined environment variable: \$CYLC_TMPDIR" >&2
+    exit 1
 fi
-mkdir -p $TMPDIR
+mkdir -p $CYLC_TMPDIR
 
 # seconds since epoch
 SSE=$( date +%s )
 
 SUITE_DEF=$CYLC_DIR/examples/admin/test
 SUITE_REG=testsuite.$SSE
-SUITE_DIR=$TMPDIR/$SUITE_REG
+SUITE_DIR=$CYLC_TMPDIR/$SUITE_REG
 
 echo -n ">> COPYING $SUITE_DEF and REGISTERING it as $SUITE_REG ... "
 cp -r $SUITE_DEF $SUITE_DIR
