allow taskscript on commandline for cylc-wrapper

diff --git a/bin/cylc-wrapper b/bin/cylc-wrapper
--- a/bin/cylc-wrapper
+++ b/bin/cylc-wrapper
@@ -10,36 +10,48 @@
 #         |________________________|
 
 
-# Cylc task wrapper script
+# Cylc task wrapper script.
 
-# Cylc tasks must send, at the least, their own 'started', 'succeeded',
-# and 'failed' messages. This script allows cylc to control existing
-# tasks that have not been modified to do their own cylc messaging.
+# This script allows cylc to control existing tasks that have not been
+# modified to do their own cylc messaging.  It can only be used for
+# tasks that:
+# (a) see their processing through till the end (as opposed to
+# submitting or spawning subprocesses and then exiting). 
+# (b) return the standard non-zeros exit status for failure. 
 
-# It does the following:
+# The task wrapper does the following:
 # (1) sends special 'started' message
 # (2) executes the wrapped task (passes any commandline on)
 # (3) sends the special 'succeed' message on completion,
 #     or the special 'failed' message if an error occurs.
 
-# It is assumed that wrapped tasks return the standard shell exit codes
-# for success or failure. Wrapped tasks can also send their own cylc
-# messages, but in that case you might as well dispense with wrapping
-# and provide the started, finished, and failed messages as well.
+# Wrapped tasks can also send their own cylc messages, which will be
+# logged by cylc, otherwise task stdout and stderr will end up in the
+# job log files, depending on the job submission method.
 
 set -e; trap 'cylc task-failed "error trapped"' ERR
 
 # send the startup message
 cylc task-started || exit 1
 
-# only need to check for $WRAP here.
-if [[ -z $WRAP ]]; then
-    cylc task-failed "ERROR, cylc-wrapper: \$WRAP not found"
+if [[ -n $WRAP ]]; then
+    # commandline now preferred but allow $WRAP for backward compatibility
+    TASK_SCRIPT=$WRAP
+elif (( $# >= 1 )); then
+    TASK_SCRIPT=$1
+    shift
+else
+    cylc task-failed "cylc-wrapper: no task script (use commandline or \$WRAP)"
     exit 1
 fi
 
+which $TASK_SCRIPT > /dev/null 2>&1 || {
+    cylc task-failed "cylc-wrapper: task script $TASK_SCRIPT not found"
+    exit 1
+}
+
 # execute the wrapped task and check for success or failure
-if $WRAP $@; then 
+if $TASK_SCRIPT $@; then 
     # succeeded
     cylc task-message --all-outputs-completed
     cylc task-finished
