Cylc command refactor

diff --git a/bin/cylc b/bin/cylc
--- a/bin/cylc
+++ b/bin/cylc
@@ -1,118 +1,109 @@
 #!/usr/bin/env bash
-# 
-# This is an experimental bash script to replace the python 'cylc' command
 #
-CATEGORIES=('control' 'information' 'all' 'task' 'license|GPL' 'admin' \
+# THIS FILE IS PART OF THE CYLC SUITE ENGINE.
+# Copyright (C) 2008-2017 NIWA
+#
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+CATEGORIES=('control' 'information' 'all' 'task' 'license' 'GPL' 'admin' \
                 'preparation' 'hook' 'discovery' 'utility')
+                
+HELP_OPTS=('help' '--help' '-h' 'h' '?')
+
 
 if ${CYLC_DEBUG:-false}; then
     set -x
 fi
 
-function print_version() {
-    #echo "Cylc $CYLC_VERSION ($CYLC_HOME)"
-    CYLC_VERSION=$($CYLC_HOME_BIN/cylc-new-version)
+get_version() {
+    # If there is a version file present, use that
+    if [[ -f $CYLC_HOME/VERSION ]]; then
+        CYLC_VERSION="$(cat $CYLC_HOME/VERSION)"
+    else
+        local DESC=
+        DESC=$(cd $CYLC_HOME && git describe 2>/dev/null)
+        CYLC_VERSION=$DESC
+    fi
+}
+
+print_version() {
+    # New way
+    get_version
+    # Old way using the python script
+    #CYLC_VERSION="$($CYLC_HOME_BIN/cylc-new-version)"
     echo "Cylc $CYLC_VERSION ($CYLC_HOME)"
 }
 
-function init_dirs() {
+init_cylc() {
     set -eu
     CYLC_HOME_BIN="$(dirname "$(readlink -f "$0")")"
-    echo $CYLC_HOME_BIN
-    # Rose has a 'canonicalize link' step here,
-    # is this needed for cylc? 
     CYLC_HOME="$(dirname "$CYLC_HOME_BIN")"
-    echo $CYLC_HOME
+    CYLC_NS="$(basename $0)"
+    CYLC_DIR="$CYLC_HOME/lib/"
     
-    # TODO
-    # This would actually be CYLC_NS=$(basename $0) in the final version
-    CYLC_NS=$(basename $0)
+    #echo $CYLC_HOME $CYLC_HOME_BIN $CYLC_HOME $CYLC_NS 
+    
+    get_version
     
     PATH=$(path_lead "${PATH:-}" "$CYLC_HOME_BIN")
     PYTHONPATH=$(path_lead "${PYTHONPATH:-}" "$CYLC_HOME/lib/")
     
-    export PATH PYTHONPATH
-    
-    #exec $CYLC_HOME/lib/cylc/version.py
+    export PATH PYTHONPATH CYLC_DIR CYLC_VERSION
 }
 
-
-function help_usage() {
-    # Call the python help script with no arguments
-    # You should get the deafult help/usage text
-    exec cylc-old
-}
-
-function help_categ() {       
-    # If category name is used, call the help func with the category
-    if [[ " ${CATEGORIES[*]} " == *" $1 "* ]]; then
-        echo "$1 is a known cylc command category."
-        local COMMAND=$CYLC_HOME_BIN/$CYLC_NS-old
-        echo "$COMMAND, $1, $@"
-        exec $COMMAND $1
+help_util() {
+    # Deals with form 'cylc [COMMAND] --help'
+    cd $CYLC_HOME_BIN
+    if [[ (($# -gt 1)) && "${HELP_OPTS[*]} " == *" $UTIL "* && " ${CATEGORIES[*]} " != *" $1 "* ]]; then
+        local COMMAND=$CYLC_HOME_BIN/cylc-$1
+        exec $COMMAND --help
         exit
     fi
-}
-
-function help_util() {
-    # Calls the 
-    echo $UTIL
-    echo "Call help function for: $UTIL"
-    # Call the python help function for the given command
-    #$UTIL
-
-    local NAME=$UTIL
-    #local COMMAND=$CYLC_HOME_BIN/$CYLC_NS $NAME
+    # Deal with cases like 'cylc --help [COMMAND/CATEGORY] or cylc [CATEGORY]'   
+    if [[ (( $# -ge 1 )) && -f "$(ls cylc-${1}*)" ]] ; then
+        local COMMAND=$CYLC_HOME_BIN/$(ls "cylc-${1}"*)
+        exec $COMMAND --help
+        exit
+    fi
+    # Deal with cases like 'cylc --help [COMMAND/CATEGORY]'
+    if [[ (( $# -gt 1 )) && -f $(ls "cylc-${2}"*)  ]] ; then
+        local COMMAND=$CYLC_HOME_BIN/$(ls "cylc-${2}"*)
+        exec $COMMAND --help
+        exit
+    fi
     
     # If category name is used, call the help func with the category
-    if [[ " ${CATEGORIES[*]} " == *" $UTIL "* || " ${CATEGORIES[*]} " == *" $1 "* ]]; then
-        local COMMAND=$CYLC_HOME_BIN/cylc-old
-        echo "$COMMAND, $1, $@"
-        exec $COMMAND $1
+    if [[ " ${CATEGORIES[*]} " == *" $UTIL "* || " ${HELP_OPTS[*]} " == *" $UTIL "* ]]; then
+        local COMMAND=$CYLC_HOME_BIN/cylc-help
+        #echo "$COMMAND, $@"
+        exec $COMMAND $@
         exit
     fi
     
     # If not a category or not an actaul command in the bin dir, exit
-    if [[ ! -r $COMMAND ]] ; then
-        echo "$1: unknown utility. Abort." >&2
+    if [[ ! -f $(ls "cylc-${UTIL}"*) ]] ; then
+        echo "$UTIL: unknown utility. Abort." >&2
         echo "Type 'cylc help' for a list of utilities."
         return 1
     fi
-    local ALIAS=$(get_alias $NAME)
-    if [[ -n $ALIAS ]]; then
-        COMMAND=$CYLC_HOME_BIN/$CYLC_NS-$ALIAS
-        COMMAND=${COMMAND%% *}
-    fi
     
-    case $(head -1 -- $COMMAND) in
-    *bash*)
-        awk '{
-            if (/^# NAME/) {
-                do {print substr($0, 3)} while (getline && !/^#----------/);
-            }
-        }' $COMMAND | ${PAGER:-less}
-        ;;
-    *python*)
-        $COMMAND --help | ${PAGER:-less} # FIXME: not too pretty at the moment
-        ;;
-    esac
-    return
-}
+    echo "Something has gone terribly wrong if you are here..."
+    return 1
 
-function get_alias() {
-    local NAME=$1
-    local ALIAS=$(sed '/^#/d' $CYLC_HOME_BIN/$CYLC_NS-$NAME || true)
-    if [[ $(wc -l <<<"$ALIAS") == 1 ]] \
-        && grep -q "^exec \$(dirname \$0)/$CYLC_NS-.* \"\$@\"\$" <<<"$ALIAS"
-    then
-        ALIAS=${ALIAS#"exec \$(dirname \$0)/$CYLC_NS-"}
-        ALIAS=${ALIAS%' "$@"'}
-        $ALIAS
-    fi
 }
 
 # Ensure that ITEM_STR is at the beginning of PATH_STR
-function path_lead() {
+path_lead() {
     local PATH_STR=$1
     local ITEM_STR=$2
     if [[ -z ${PATH_STR:-} ]]; then
@@ -131,7 +122,21 @@ function path_lead() {
         echo "$PATH_STR"
     fi
 }
-init_dirs
+
+abort_bad_command() {
+    echo "$CYLC_NS: $UTIL: unknown utility. Abort." >&2
+    echo "Type \"$CYLC_NS help all\" for a list of utilities." >&2
+    exit 1
+}
+
+abort_ambiguous_command() {
+    echo "\"$UTIL\" is too ambiguous to be a valid Cylc command abbreviation."
+    echo "These commands match the abbreviation \"$UTIL\":"
+    ls "cylc-${UTIL}"* 2>/dev/null | sed -r 's/cylc-//'
+    exit 1
+}
+
+init_cylc
 
 UTIL="help"
 if (($# > 0)); then
@@ -141,50 +146,30 @@ fi
 
 case $UTIL in
 help|h|?|--help|-h)
-    if (($# == 0)); then
-        {
-            print_version
-            #cylc_usage
-            
-            # Call the basic usage help
-            help_usage
-        } | ${PAGER:-less}
-        exit 0
-    fi
-#    RC=0
-#    for U in "$@"; do
-#        if [[ $U == 'help' || $U == 'version' ]]; then
-#            continue
-#        fi
-#        help_util $U || RC=$?
-#    done
-#    exit $RC
+    help_util $@
+    exit
     :;;
 version|--version|-V)
     print_version
     exit
     :;;
 control|information|all|task|license|GPL|admin|preparation|hook|discovery|utility)
-    echo "CATEGORIES HAVE BEEN CALLED"
-    echo "Util: $UTIL, Args: $@"
-    help_util $UTIL $@
+    help_util $UTIL
     exit
     :;;
 esac
 
-COMMAND=$(dirname $0)/$CYLC_NS-$UTIL
-echo $COMMAND
+# Abort if no matches to command abbrev, list matches if multiple matches
+test "$(ls "$CYLC_HOME_BIN/cylc-${UTIL}"* 2>/dev/null)" || { abort_bad_command; }
+test "$(ls "$CYLC_HOME_BIN/cylc-${UTIL}"* | wc -l )" -gt 1 && { abort_ambiguous_command; }
+
+COMMAND=$(ls "$CYLC_HOME_BIN/cylc-${UTIL}"*)
+
 if [[ ! -f $COMMAND || ! -x $COMMAND ]]; then
-    echo "$CYLC_NS: $UTIL: unknown utility. Abort." >&2
-    echo "Type \"$CYLC_NS help\" for a list of utilities." >&2
-    exit 1
+    abort_bad_command
 fi
-#if (($# > 0)) && [[ $1 == '--help' || $1 == '-h' ]]; then
-#    help_util
-#    exit
-#fi
 
 CYLC_UTIL=$UTIL
 export CYLC_UTIL
 
-exec $COMMAND "$@"
+exec "$COMMAND" "$@"
