cylc help CAT CMD: fix abbr CMD usage

diff --git a/bin/cylc b/bin/cylc
--- a/bin/cylc
+++ b/bin/cylc
@@ -74,20 +74,19 @@ help_util() {
     fi
     # For help command/option with no args
     if [[ $# == 0 && "${HELP_OPTS[*]} " == *"$UTIL"* ]]; then
-        exec "${CYLC_HOME_BIN}"/cylc-help
+        exec "${CYLC_HOME_BIN}/cylc-help"
     fi
     # for cases 'cylc --help CATEGORY COMMAND'
     if [[ $# -gt 1 &&  "${HELP_OPTS[*]} " == *"$UTIL"* && \
           " ${CATEGORIES[*]} " == *" $1 "* ]]; then
-        local COMMAND="${CYLC_HOME_BIN}/cylc-$2"
-        exec "${COMMAND}" "--help"  
+        UTIL="$(get_command_from_abbr "$2")"
+        run_cylc_command '--help'
     fi
     # Check if this is a help command, not containing a category qualifier
     if [[ $# -gt 1  && "${HELP_OPTS[*]} " == *"${UTIL}"* && 
           " ${CATEGORIES[*]} " != *" $1 "* &&
           " ${CATEGORIES[*]} " != *" $2 "* ]]; then
-        local COMMAND="${CYLC_HOME_BIN}/cylc-${UTIL}"
-        exec "${COMMAND}" "--help"
+        run_cylc_command '--help'
     fi
     # If category name is used, call the help func with the category
     # make this deal with 'cylc help CATEGORY' only
@@ -95,8 +94,8 @@ help_util() {
           || " ${HELP_OPTS[*]} " == *" ${UTIL} "* \
           && $# -gt 0 && ( " ${CATEGORIES[*]} " == *" $1 "* \
           || " ${HELP_OPTS[*]} " == *" $1 "* ) ]]; then
-        local COMMAND="${CYLC_HOME_BIN}/cylc-help"
-        exec "${COMMAND}" "$@"
+        UTIL='help'
+        run_cylc_command "$@"
     fi
     # Deal with cases like 'cylc --help [COMMAND/CATEGORY] or cylc [CATEGORY]'   
     if (( $# >= 1 )); then
@@ -110,13 +109,9 @@ Options:
   --long            print cylc version and location of cylc installation
 __HELP__
             return
-        elif test -x "cylc-$1"*; then
-            local COMMAND="${CYLC_HOME_BIN}/$(echo "cylc-$1"*)"
-            exec "${COMMAND}" '--help'
-        elif (( "$(wc -l <<<"$(ls cylc-$1* 2>/dev/null)")" > 1 )); then
-            abort_ambiguous_command "$1"
         else
-            abort_bad_command "$1"
+            UTIL="$(get_command_from_abbr "$1")"
+            run_cylc_command '--help'
         fi
     fi
     # If category name is used as arg, call the help func with the category
@@ -175,30 +170,26 @@ path_lead() {
     fi
 }
 
-abort_bad_command() {
-    CYLC_NS="$(basename $0)"
-    echo "${CYLC_NS}: $1: unknown utility. Abort." >&2
-    echo "Type \"${CYLC_NS} help all\" for a list of utilities." >&2
-    exit 1
-}
-
-abort_ambiguous_command() {
-    echo "\"$1\" is ambiguous." >&2
-    echo "These commands match the abbreviation \"$1\":" >&2
-    sed "s,${CYLC_HOME_BIN}/cylc-,," \
-        <<<"$(ls "${CYLC_HOME_BIN}/cylc-$1"* 2>/dev/null)" >&2
-    exit 1
-}
-
-run_cylc_command_matched() {
-    CYLC_UTIL="$(sed "s,${CYLC_HOME_BIN}/cylc-,," <<<"${commands_match}")"
-    export CYLC_UTIL
-    exec "${commands_match}" "$@"
+get_command_from_abbr() {
+    local ABBR="$1"
+    local COMMAND="$(cd "${CYLC_HOME_BIN}" && ls "cylc-$1"* 2>'/dev/null')"
+    if (("$(wc -l <<<"${COMMAND}")" == 1)); then
+        # Abbreviation has one match, good
+        sed 's/^cylc-//' <<<"${COMMAND}"
+        return
+    elif (("$(wc -l <<<"${COMMAND}")" == 0)); then
+        # Abbreviation has no match, bad
+        echo "cylc $1: unknown utility. Abort." >&2
+        echo "Type \"cylc help all\" for a list of utilities." >&2
+    else
+        # Abbreviation has multiple matches, bad
+        echo "cylc $1: is ambiguous for:" >&2
+        sed 's/^/    cylc /' <<<"${COMMAND}" >&2
+    fi
+    return 1
 }
 
 run_cylc_command() {
-    CYLC_UTIL="${UTIL}"
-    export CYLC_UTIL
     exec "${CYLC_HOME_BIN}/cylc-${UTIL}" "$@"
 }
 
@@ -211,7 +202,7 @@ if (( $# > 0 )); then
 fi
 # For speed, assume a correct command has been provided first of all. 
 if [[ -f "${CYLC_HOME_BIN}/cylc-${UTIL}" && "${UTIL}" != 'help'  ]]; then
-    run_cylc_command "$@" 
+    run_cylc_command "$@"
 fi
 
 # Now process help and command matching.
@@ -251,27 +242,5 @@ esac
 
 # User has not given a help, category, or version option.
 # So now deal with matching commands and disambiguation.
-
-# Store any matching file glob as a number for later use
-# Minimises re-running ls
-if commands_match="$(ls "${CYLC_HOME_BIN}/cylc-${UTIL}"* 2>'/dev/null')"; then
-    num_commands_match="$(wc -l <<<"${commands_match}")"
-else
-    num_commands_match=0
-fi
-
-# Abort if no matches to command abbrev, list matches if multiple matches
-if (( "$num_commands_match" == 0 )); then
-    abort_bad_command "${UTIL}"
-# Now try and match abbreviated commands.
-elif (( "$num_commands_match" == 1 )); then
-    run_cylc_command_matched "$@"
-# Abort if the command wildcard match is ambiguous, unless it is itself a 
-# command, e.g. "cylc graph" matches "cylc-graph" and "cylc-graph-diff",
-# but the command should not abort in this case.  
-elif [[ "$num_commands_match" -gt 1 && -f "${CYLC_HOME_BIN}/cylc-${UTIL}" ]]
-then
-    exec "${CYLC_HOME_BIN}/cylc-${UTIL}" "@"
-else
-    abort_ambiguous_command "${UTIL}"
-fi
+UTIL="$(get_command_from_abbr "${UTIL}")"
+run_cylc_command "$@"
