actions: install mail

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -19,7 +19,7 @@ jobs:
       - name: Apt-Get
         run: |
           sudo apt-get update
-          sudo apt-get install -y shellcheck sqlite3 s-nail
+          sudo apt-get install -y shellcheck sqlite3
       - name: Install
         run: |
           pip install ."[all]"
@@ -51,13 +51,26 @@ jobs:
       - name: Apt-Get
         run: |
           sudo apt-get update
-          sudo apt-get install -y sqlite3 s-nail
+          sudo apt-get install -y sqlite3
+      - name: Setup Mail
+        run: |
+          sudo apt-get install -y debconf-utils
+          echo "postfix postfix/main_mailer_type select Local only" | \
+            sudo debconf-set-selections
+          sudo apt-get install -y mailutils
+      - name: Mail-Test
+        run: |
+          echo test | mail -s test runner
+          mail -H
       - name: Install
         run: |
           pip install ."[all]"
       - name: Test
         run: |
-          etc/bin/run-functional-tests -j 8
+          etc/bin/run-functional-tests -j 8 --state=save || (
+            echo '=== Re-running Failed Tests'
+            CHUNK= etc/bin/run-functional-tests -j 8 --state=save,failed
+          )
       - name: Debug
         if: failure()
         run: |
